const KEY='qisttak_v1_data';
let db=JSON.parse(localStorage.getItem(KEY)||'{"customers":[],"contracts":[],"payments":[],"expenses":[]}');
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const REMINDER_KEY='qisttak_reminder_days';
const getReminderDays=()=>+(localStorage.getItem(REMINDER_KEY)||5);
const saveReminderDays=()=>{localStorage.setItem(REMINDER_KEY, reminderDays.value);renderReminders();};
// ترقية العقود القديمة لإضافة تاريخ بداية دون فقدان البيانات
db.contracts.forEach(c=>{if(!c.startDate)c.startDate=(c.startMonth?c.startMonth+'-01':today());});
save();
const money=n=>new Intl.NumberFormat('ar-IQ').format(Math.round(n||0))+' د.ع';
const id=()=>Date.now()+Math.random().toString(16).slice(2);
const today=()=>new Date().toISOString().slice(0,10);
function go(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(p).classList.add('active');if(p==='home')renderHome();if(p==='customers')renderCustomers();if(p==='contracts')renderContracts();if(p==='reports')renderReport();if(p==='reminders')renderReminders()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));
function openModal(html){document.getElementById('modalContent').innerHTML=html;document.getElementById('modal').style.display='block'}
function closeModal(){document.getElementById('modal').style.display='none'}
function openNewCustomer(){openModal(`<h2>إضافة زبون</h2><label>الاسم</label><input id="cn"><label>رقم الهاتف</label><input id="cp" inputmode="tel"><label>ملاحظات</label><input id="cm"><button onclick="addCustomer()">حفظ</button>`)}
function addCustomer(){let name=cn.value.trim(),phone=cp.value.trim();if(!name||!phone)return alert('أدخل الاسم ورقم الهاتف');db.customers.push({id:id(),name,phone,note:cm.value.trim(),archived:false,created:today()});save();closeModal();go('customers')}
function openNewContract(){if(!db.customers.length)return alert('أضف زبوناً أولاً');let opts=db.customers.filter(c=>!c.archived).map(c=>`<option value="${c.id}">${c.name} — ${c.phone}</option>`).join('');openModal(`<h2>عقد جديد</h2><label>الزبون</label><select id="cid">${opts}</select><label>السلعة</label><input id="prod" placeholder="مثلاً iPhone"><div class="grid"><div><label>سعر الشراء</label><input id="buy" type="number" value="0"></div><div><label>ربحك على السلعة</label><input id="profit" type="number" value="0"></div><div><label>نسبة التحميل %</label><input id="rate" type="number" value="30"></div><div><label>المقدم</label><input id="down" type="number" value="0"></div><div><label>تاريخ بداية الأقساط</label><input id="startDate" type="date" value="${today()}"></div><div><label>عدد الأشهر</label><input id="months" type="number" value="10" min="1"></div></div><div class="panel" id="preview">أدخل الأرقام</div><button onclick="createContract()">إنشاء العقد</button>`);['buy','profit','rate','down','months'].forEach(x=>document.getElementById(x).oninput=previewContract);previewContract()}
function calc(){let b=+buy.value||0,p=+profit.value||0,r=(+rate.value||0)/100,d=+down.value||0,m=Math.max(1,+months.value||1),base=b+p,load=base*r,total=base+load,remain=Math.max(0,total-d);return {b,p,r,d,m,base,load,total,remain,payment:remain/m}}
function previewContract(){let x=calc();document.getElementById('preview').innerHTML=`<div class="row"><span>سعر الأساس</span><b>${money(x.base)}</b></div><div class="row"><span>التحميل</span><b>${money(x.load)}</b></div><div class="row"><span>الإجمالي</span><b>${money(x.total)}</b></div><div class="row"><span>المتبقي بعد المقدم</span><b>${money(x.remain)}</b></div><div class="row"><span>القسط الشهري</span><b>${money(x.payment)}</b></div>`}
function createContract(){let x=calc();if(x.total<=0||x.m<1)return alert('راجع البيانات');let start=startDate.value||today();let c={id:id(),customerId:cid.value,product:prod.value.trim()||'سلعة',buy:x.b,profit:x.p,rate:x.r,total:x.total,base:x.base,load:x.load,down:x.d,months:x.m,startDate:start,startMonth:start.slice(0,7),status:'active',created:today(),deferred:[],adjustments:[]};db.contracts.push(c);if(x.d>0)db.payments.push({id:id(),contractId:c.id,amount:x.d,date:today(),type:'down'});save();closeModal();go('contracts')}
function paid(c){return db.payments.filter(p=>p.contractId===c.id).reduce((s,p)=>s+p.amount,0)}
function remaining(c){return Math.max(0,c.total-paid(c))}
function renderHome(){let totalDebt=db.contracts.reduce((s,c)=>s+remaining(c),0),received=db.payments.reduce((s,p)=>s+p.amount,0),profit=db.contracts.reduce((s,c)=>s+c.profit,0),load=db.contracts.reduce((s,c)=>s+c.load,0),late=db.contracts.filter(c=>remaining(c)>0&&status(c)==='متأخر').length;stats.innerHTML=[['👥 الزبائن',db.customers.length,''],['💰 الربح',money(profit),'orange'],['💵 المقبوض',money(received),'green'],['🧾 الديون/المتبقي',money(totalDebt),'orange'],['🟠 التحميل',money(load),''],['🔴 المتأخرون',late,'red']].map(a=>`<div class="card ${a[2]}">${a[0]}<strong>${a[1]}</strong></div>`).join('');alerts.innerHTML=late?`<div class="item">🔴 لديك <b>${late}</b> عقد متأخر.</div>`:'<div class="item">لا توجد متأخرات حالياً ✅</div>'}
function renderCustomers(){let q=(customerSearch?.value||'').toLowerCase();let arr=db.customers.filter(c=>!c.archived&&(c.name.toLowerCase().includes(q)||c.phone.includes(q)));customerList.innerHTML=arr.map(c=>{let cs=db.contracts.filter(x=>x.customerId===c.id),rem=cs.reduce((s,x)=>s+remaining(x),0);return `<div class="item"><h3>${c.name}</h3><div class="muted">${c.phone}</div><div class="row"><span>العقود: ${cs.length}</span><b>${money(rem)}</b></div><button onclick="customerView('${c.id}')">فتح الحساب</button></div>`}).join('')||'<p>لا توجد نتائج</p>'}
function customerView(cid){let c=db.customers.find(x=>x.id===cid),cs=db.contracts.filter(x=>x.customerId===cid);openModal(`<h2>${c.name}</h2><p>${c.phone}</p><p>إجمالي المتبقي: <b>${money(cs.reduce((s,x)=>s+remaining(x),0))}</b></p>${cs.map(x=>`<div class="item"><b>${x.product}</b><br>المتبقي: ${money(remaining(x))}<br><button onclick="contractView('${x.id}')">تفاصيل العقد</button></div>`).join('')}<button class="secondary" onclick="archiveCustomer('${cid}')">أرشفة الزبون</button>`)}
function archiveCustomer(cid){if(db.contracts.some(c=>c.customerId===cid&&remaining(c)>0))return alert('لا يمكن أرشفة زبون عليه متبقي');db.customers.find(c=>c.id===cid).archived=true;save();closeModal();renderCustomers()}
function renderContracts(){let q=(contractSearch?.value||'').toLowerCase();let arr=db.contracts.filter(c=>{let n=db.customers.find(x=>x.id===c.customerId)?.name||'';return n.toLowerCase().includes(q)||c.product.toLowerCase().includes(q)});contractList.innerHTML=arr.map(c=>{let n=db.customers.find(x=>x.id===c.customerId)?.name||'-';return `<div class="item"><h3>${n} — ${c.product}</h3><span class="status ${remaining(c)===0?'paid':status(c)==='متأخر'?'late':'due'}">${remaining(c)===0?'مكتمل':status(c)}</span><div class="row"><span>الإجمالي</span><b>${money(c.total)}</b></div><div class="row"><span>المتبقي</span><b>${money(remaining(c))}</b></div><button onclick="contractView('${c.id}')">فتح العقد</button></div>`}).join('')||'<p>لا توجد عقود</p>'}
function status(c){if(remaining(c)<=0)return 'مكتمل';let d=nextDue(c);if(!d)return 'مكتمل';let due=new Date(d.date+'T00:00:00');let now=new Date();now.setHours(0,0,0,0);let end=new Date(due);end.setDate(5);if(now>end)return 'متأخر';if(now>=due&&now<=end)return 'مستحق';return 'قادم'}
function formatDate(d){return new Date(d+'T00:00:00').toLocaleDateString('ar-IQ',{year:'numeric',month:'2-digit',day:'2-digit'})}function dueDate(c,i){let parts=(c.startDate||today()).split('-').map(Number),y=parts[0],m=parts[1]-1;let target=new Date(y,m+i,1);return target.toISOString().slice(0,10)}function contractRows(c,p,monthly){let rows='',paidCount=Math.min(c.months,Math.floor((p+0.0001)/monthly));rows+=`<div class="installment-head"><span>#</span><span>تاريخ الاستحقاق</span><span>القسط</span><span>الحالة</span></div>`;for(let i=1;i<=c.months;i++){let due=Math.round(monthly),ds=dueDate(c,i);let st=i<=paidCount?'مدفوع':(new Date(ds+'T23:59:59')<new Date()?'متأخر':i===paidCount+1?'مستحق':'قادم');rows+=`<div class="installment-card ${st==='متأخر'?'is-late':st==='مستحق'?'is-due':st==='مدفوع'?'is-paid':''}"><b class="num">${i}</b><span class="date">📅 ${formatDate(ds)}</span><b class="amount">${money(due)}</b><span class="status ${st==='مدفوع'?'paid':st==='متأخر'?'late':'due'}">${st}</span></div>`}return `<div class="installments-table">${rows}</div>`}function contractView(cid){let c=db.contracts.find(x=>x.id===cid),n=db.customers.find(x=>x.id===c.customerId)?.name||'-',p=paid(c),rem=remaining(c),monthly=(c.total-c.down)/c.months;let rows=contractRows(c,p,monthly);openModal(`<h2>${n} — ${c.product}</h2><div class="panel"><div class="row"><span>سعر الأساس</span><b>${money(c.base)}</b></div><div class="row"><span>التحميل</span><b>${money(c.load)}</b></div><div class="row"><span>الإجمالي</span><b>${money(c.total)}</b></div><div class="row"><span>المقدم</span><b>${money(c.down)}</b></div><div class="row"><span>المدفوع</span><b>${money(p)}</b></div><div class="row"><span>المتبقي</span><b>${money(rem)}</b></div></div><h3>جدول الأقساط</h3>${rows}<div class="quick"><button onclick="addPayment('${cid}')">💵 تسجيل دفعة</button><button onclick="sendWhatsApp('${cid}')">📲 إرسال للواتساب</button><button onclick="sendReminder('${cid}')">🔔 تذكير القسط</button><button onclick="deferOne('${cid}')">⏸️ تأجيل قسط</button><button onclick="earlyPay('${cid}')">✅ تسديد مبكر</button></div>`)}
function sendWhatsApp(cid){let c=db.contracts.find(x=>x.id===cid),n=db.customers.find(x=>x.id===c.customerId);if(!n)return;let p=paid(c),rem=remaining(c),monthly=(c.total-c.down)/c.months;let lines=[`مرحباً ${n.name} 🌹`,`تفاصيل حسابك في قسطتك (GestTec):`,`السلعة: ${c.product}`,`إجمالي العقد: ${money(c.total)}`,`المقدم: ${money(c.down)}`,`المدفوع: ${money(p)}`,`المتبقي: ${money(rem)}`,`القسط الشهري: ${money(monthly)}`,``,`📅 جدول الأقساط`,`────────────────────`,`رقم | الاستحقاق | المبلغ | الحالة`,`────────────────────`];for(let i=1;i<=c.months;i++){let due=Math.round(monthly),ds=dueDate(c,i),paidCount=Math.min(c.months,Math.floor((p+0.0001)/monthly));let today0=new Date();today0.setHours(0,0,0,0);let d0=new Date(ds+'T00:00:00');let end=new Date(d0);end.setDate(5);let st=i<=paidCount?'مدفوع':today0>end?'متأخر':today0>=d0?'مستحق':'قادم';lines.push(`${String(i).padStart(2,' ')} | ${formatDate(ds)} | ${money(due)} | ${st}`)}lines.push(`────────────────────`);let phone=(n.phone||'').replace(/[^0-9+]/g,'');let url='https://wa.me/'+phone.replace(/^0/,'964')+'?text='+encodeURIComponent(lines.join('\n'));window.open(url,'_blank')}
function nextDue(c){let p=paid(c),monthly=(c.total-c.down)/c.months,paidCount=Math.min(c.months,Math.floor((p+0.0001)/monthly));if(p>=c.total||paidCount>=c.months)return null;let i=paidCount+1;return {i,date:dueDate(c,i),amount:Math.round(monthly)};}
function renderReminders(){let el=document.getElementById('reminderList');if(!el)return;let sel=document.getElementById('reminderDays');if(sel)sel.value=String(getReminderDays());let days=getReminderDays(),now=new Date();now.setHours(0,0,0,0);let until=new Date(now);until.setDate(until.getDate()+days);let rows=[];db.contracts.forEach(c=>{let n=db.customers.find(x=>x.id===c.customerId);let d=nextDue(c);if(!n||!d)return;let due=new Date(d.date+'T00:00:00');if(due>=now&&due<=until)rows.push({c,n,d,delta:Math.round((due-now)/86400000)});});rows.sort((a,b)=>a.d.date.localeCompare(b.d.date));el.innerHTML=rows.length?rows.map(x=>`<div class="reminder-card"><div><h3>🔔 ${x.n.name}</h3><div class="muted">${x.n.phone} — ${x.c.product}</div><div class="reminder-date">القسط ${x.d.i} • ${formatDate(x.d.date)} • ${money(x.d.amount)}</div><span class="reminder-badge">بعد ${x.delta===0?'اليوم':x.delta+' أيام'}</span></div><button onclick="sendReminder('${x.c.id}')">📲 إرسال تذكير</button></div>`).join(''):'<div class="item">لا توجد أقساط ضمن فترة التذكير الحالية ✅</div>'}
function sendReminder(cid){let c=db.contracts.find(x=>x.id===cid),n=db.customers.find(x=>x.id===c.customerId),d=nextDue(c);if(!n||!d)return;let lines=[`مرحباً ${n.name} 🌹`,`🔔 تذكير بدفع القسط`,`المبلغ: ${money(d.amount)}`,`فترة السداد: من ${formatDate(d.date)} إلى ${formatDate(d.date.slice(0,8)+'05')}`,`القسط رقم: ${d.i} من ${c.months}`,``,`نرجو تسديد القسط خلال فترة السداد.`,`نعتذر في حال تم الدفع مسبقاً.`,`شكراً لتعاملك معنا`,`قسطتك - GestTec`];let phone=(n.phone||'').replace(/[^0-9+]/g,'');let url='https://wa.me/'+phone.replace(/^0/,'964')+'?text='+encodeURIComponent(lines.join('\n'));window.open(url,'_blank')}
function addPayment(cid){openModal(`<h2>تسجيل دفعة</h2><label>المبلغ</label><input id="pa" type="number"><label>التاريخ</label><input id="pd" type="date" value="${today()}"><button onclick="savePayment('${cid}')">حفظ الدفعة</button>`)}
function savePayment(cid){let a=+pa.value;if(a<=0)return alert('أدخل مبلغاً صحيحاً');db.payments.push({id:id(),contractId:cid,amount:a,date:pd.value,type:'payment'});save();closeModal();contractView(cid)}
function deferOne(cid){let c=db.contracts.find(x=>x.id===cid);c.deferred.push({date:today(),count:1});c.months+=1;save();contractView(cid)}
function earlyPay(cid){let c=db.contracts.find(x=>x.id===cid),r=remaining(c);if(r<=0)return;let a=prompt('مبلغ التسديد المبكر',r);a=+a;if(a!==r)return alert('لإغلاق العقد يجب تسجيل كامل المتبقي');db.payments.push({id:id(),contractId:cid,amount:a,date:today(),type:'early'});save();closeModal();renderContracts()}
function renderReport(){let profit=db.contracts.reduce((s,c)=>s+c.profit,0),load=db.contracts.reduce((s,c)=>s+c.load,0),received=db.payments.reduce((s,p)=>s+p.amount,0),debt=db.contracts.reduce((s,c)=>s+remaining(c),0);report.innerHTML=`<div class="row"><span>ربح السلع</span><b>${money(profit)}</b></div><div class="row"><span>إجمالي التحميل</span><b>${money(load)}</b></div><div class="row"><span>المقبوض</span><b>${money(received)}</b></div><div class="row"><span>المتبقي/الديون</span><b>${money(debt)}</b></div><p class="muted">هذه نسخة أولية؛ المصاريف والصندوق الكامل والتقارير المتقدمة ستكون في المرحلة التالية.</p>`}
function tick(){clock.textContent=new Date().toLocaleString('ar-IQ',{dateStyle:'medium',timeStyle:'short'})}setInterval(tick,1000);tick();renderHome();
